server:
  port: 8085

spring:
  application:
    name: dubbo-consumer

dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.159.131:2181
    protocol: zookeeper
    timeout: 10000
