server:
  port: 8080
  servlet:
    context-path: /dp

spring:
  application:
    name: dubbo-provider

dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.159.131:2181
    protocol: zookeeper
    timeout: 10000
